### ISSUE TITLE
Unable to copy paste code copied from firefox into editor

### ISSUE THREAD

**Issue by PtrMan** [Calinou/gdscript-online#5]
I am running firefo under linux.<br />
I tried to copy some complicated code from gist.github.com to the editor but it doesn't handle the clipboard like any sane editor should.

**Comment by Calinou** [comment]
This is a Godot bug. It *might* be fixed in the 3.2.4 betas, but I'm not sure as clipboard support in HTML5 is really difficult to get right: https://github.com/godotengine/godot/pull/29298

In the meantime, try using a Chromium-based browser, it might work better.

**Comment by SlitheringMule** [comment]
Still present, I think it might be a clipboard-reading permissions issue, as Edge (Chromium) requests permission to read the clipboard data), but this does not happen on other websites, such as GitHub.

**Comment by Calinou** [comment]
> but this does not happen on other websites, such as GitHub.

Other websites don't need to use the clipboard API when you press <kbd>Ctrl + C</kbd> or <kbd>Ctrl + V</kbd>, since they use native DOM rendering, not a canvas rendered via WebAssembly.

Also, the hosted version of GDScript Online isn't updated to Godot 3.3 yet – it's still on 3.2.3 as of writing.

**Comment by CoderDood** [comment]
@Calinou try using chrome and click allow to read your clipboard and you will see the text you pasted but if you did'nt click ctrl+v
at the same time!!

**Comment by CoderDood** [comment]
worked?

**Comment by Calinou** [comment]
> @Calinou try using chrome and click allow to read your clipboard and you will see the text you pasted but if you did'nt click ctrl+v at the same time!!

I've found that using the right-click → **Copy/Paste** TextEdit contextual menu works more reliably, but it still only works in Chromium-based browsers in my experience.

**Comment by CoderDood** [comment]
I tried using ctrl c and ctrl v and it works fast and no probs

**Comment by CoderDood** [comment]
are u using windows??

**Comment by CoderDood** [comment]
it has sticky keys so u can type with on hand

**Comment by CoderDood** [comment]
1

**Comment by CoderDood** [comment]
click shift 5 times in a row

**Comment by CoderDood** [comment]
then click ctrl and c and ctrl and v but no need to press them at the same time

**Comment by CoderDood** [comment]
@Calinou

**Comment by Calinou** [comment]
@CoderDood Please use the **Edit** button (hidden behind the **…** icon on the right of your comments) instead of multi-posting.

**Comment by LinuxUserGD** [comment]
Should work with custom firefox config, see https://github.com/godotengine/godot/issues/57382#issuecomment-1262280650

**Comment by VojtaStruhar** [comment]
I think this is working now. The browser asked me if I wanted to allow the website access to my clipboard and after allowing it works fine!

Windows, Chrome

**Comment by Calinou** [comment]
This was likely fixed by the update to Godot 4.3 (which has had a lot of web platform changes since 3.5.2), closing.
